// mobile/app/foglalas/[slug].tsx
import { useQuery } from '@tanstack/react-query'
import { router, useLocalSearchParams } from 'expo-router'
import { useMemo, useState } from 'react'
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { api, ApiError } from '../../src/api/client'
import { useAuth } from '../../src/auth/AuthContext'
import { colors, formatFt, formatDateTime, formatTime, radius, spacing } from '../../src/theme'
import { Button, Card, ErrorBox, Field, H2, Loading, Muted, Row } from '../../src/ui'

/**
 * Foglalási folyamat: szakember -> nap -> időpont -> adatok -> megerősítés.
 *
 * Ugyanazt a két végpontot használja, mint a weboldal: az /api/availability
 * számolja a szabad sávokat (a tesztelt motorból), az /api/appointments/hold
 * pedig tranzakciós zárolással foglal. Így egy foglalási szabály megváltozása
 * automatikusan érvényes az appban is – nincs két, egymástól elcsúszó logika.
 */

type Service = {
  id: number
  slug: string
  title: string
  desc: string
  price: number
  time: number
  vatRate: number
}

type Slot = { start: string; end: string; roomId: number }
type Practitioner = { practitionerId: number; practitionerName: string; slots: Slot[] }
type Availability = { serviceId: number; durationMin: number; practitioners: Practitioner[] }

type Settlement = 'ON_SITE' | 'PASS' | 'ONLINE_CARD'

const SETTLEMENTS: { value: Settlement; label: string; hint: string }[] = [
  {
    value: 'ON_SITE',
    label: 'Fizetés a helyszínen',
    hint: 'Készpénzzel vagy bankkártyával a rendelőben.',
  },
  {
    value: 'PASS',
    label: 'Bérletből levonás',
    hint: 'Ha van érvényes bérleted a kezelésre, a rendszer levon egy alkalmat.',
  },
  {
    value: 'ONLINE_CARD',
    label: 'Bankkártyás fizetés',
    hint: 'A foglalás a sikeres fizetéssel véglegesül.',
  },
]

/** A következő 14 nap – ennyire előre érdemes kínálni időpontot. */
const DAYS_AHEAD = 14

export default function BookingScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>()
  const { user } = useAuth()

  const [practitionerId, setPractitionerId] = useState<number | null>(null)
  const [day, setDay] = useState<string | null>(null)
  const [start, setStart] = useState<string | null>(null)
  const [settlement, setSettlement] = useState<Settlement | null>(null)
  const [form, setForm] = useState({ lastName: '', firstName: '', email: '', phone: '', note: '' })
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')
  const [result, setResult] = useState<{ publicRef: string; startsAt: string } | null>(null)

  const service = useQuery({
    queryKey: ['service', slug],
    queryFn: () =>
      api<{ product: Service }>(`/api/products?slug=${encodeURIComponent(String(slug))}`, {
        anonymous: true,
      }).then((r) => r.product),
    enabled: !!slug,
  })

  const range = useMemo(() => {
    const from = new Date()
    const to = new Date(from.getTime() + DAYS_AHEAD * 86400_000)
    return { from: from.toISOString(), to: to.toISOString() }
  }, [])

  const availability = useQuery({
    queryKey: ['availability', service.data?.id, range.from],
    queryFn: () =>
      api<Availability>(
        `/api/availability?serviceId=${service.data!.id}&from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`,
        { anonymous: true },
      ),
    enabled: !!service.data?.id,
    // A szabad időpont gyorsan avul: amíg a felhasználó gondolkodik, más
    // lefoglalhatja. Ezért itt nincs hosszú gyorsítótár.
    staleTime: 0,
  })

  if (service.isPending) return <Loading label="Kezelés betöltése…" />
  if (service.isError) {
    return (
      <View style={st.page}>
        <ErrorBox message={(service.error as ApiError).message} />
      </View>
    )
  }

  const svc = service.data
  const practitioners = availability.data?.practitioners ?? []
  const chosen = practitioners.find((p) => p.practitionerId === practitionerId) ?? null

  // Napok, amelyeken a kiválasztott szakembernek van szabad sávja.
  const daysWithSlots = new Map<string, Slot[]>()
  for (const slot of chosen?.slots ?? []) {
    const key = new Date(slot.start).toLocaleDateString('sv-SE', { timeZone: 'Europe/Budapest' })
    const list = daysWithSlots.get(key) ?? []
    list.push(slot)
    daysWithSlots.set(key, list)
  }
  const daySlots = day ? (daysWithSlots.get(day) ?? []) : []

  async function submit() {
    if (!settlement || !start) return
    setSubmitting(true)
    setError('')
    try {
      const res = await api<{ publicRef: string; startsAt: string }>(
        '/api/appointments/hold',
        {
          // Bejelentkezve a szerver a munkamenetből tudja, ki foglal; vendégként
          // a megadott adatokból hoz létre fiókot.
          anonymous: !user,
          body: {
            serviceId: svc.id,
            practitionerId,
            startsAt: start,
            settlement,
            note: form.note || undefined,
            customer: user
              ? undefined
              : {
                  lastName: form.lastName,
                  firstName: form.firstName,
                  email: form.email,
                  phone: form.phone,
                },
          },
        },
      )
      setResult(res)
    } catch (e) {
      setError(e instanceof ApiError ? e.message : 'A foglalás nem sikerült.')
      // Ha az idősáv közben elkelt, ne kínáljuk fel újra: frissítjük a naptárat
      // és visszalépünk az időpontválasztáshoz.
      setStart(null)
      void availability.refetch()
    } finally {
      setSubmitting(false)
    }
  }

  if (result) {
    return (
      <ScrollView contentContainerStyle={st.page}>
        <Card>
          <H2>Sikeres foglalás</H2>
          <Muted>A visszaigazolást e-mailben is elküldtük.</Muted>
          <View style={{ marginTop: spacing.md }}>
            <Row label="Azonosító" value={result.publicRef} />
            <Row label="Kezelés" value={svc.title} />
            <Row label="Időpont" value={formatDateTime(result.startsAt)} />
          </View>
          <View style={{ marginTop: spacing.lg, gap: spacing.sm }}>
            <Button label="Foglalásaim" onPress={() => router.replace('/foglalasaim')} />
            <Button
              label="További kezelések"
              variant="secondary"
              onPress={() => router.replace('/')}
            />
          </View>
        </Card>
      </ScrollView>
    )
  }

  return (
    <ScrollView contentContainerStyle={st.page} keyboardShouldPersistTaps="handled">
      <Card>
        <H2>{svc.title}</H2>
        <Muted>
          {svc.time} perc · {formatFt(svc.price)}
        </Muted>
      </Card>

      {availability.isPending && <Loading label="Szabad időpontok keresése…" />}

      {availability.isError && (
        <ErrorBox
          message={(availability.error as ApiError).message}
          onRetry={() => void availability.refetch()}
        />
      )}

      {availability.isSuccess && practitioners.length === 0 && (
        <Card>
          <Muted>
            Ehhez a kezeléshez jelenleg nincs online foglalható időpont. Kérlek hívj minket, és
            telefonon egyeztetünk.
          </Muted>
        </Card>
      )}

      {practitioners.length > 0 && (
        <Card>
          <H2>Szakember</H2>
          <View style={st.optionRow}>
            {practitioners.map((p) => (
              <Pressable
                key={p.practitionerId}
                accessibilityRole="button"
                accessibilityState={{ selected: practitionerId === p.practitionerId }}
                onPress={() => {
                  setPractitionerId(p.practitionerId)
                  setDay(null)
                  setStart(null)
                }}
                style={[st.option, practitionerId === p.practitionerId && st.optionOn]}
              >
                <Text
                  style={[
                    st.optionText,
                    practitionerId === p.practitionerId && st.optionTextOn,
                  ]}
                >
                  {p.practitionerName}
                </Text>
              </Pressable>
            ))}
          </View>
        </Card>
      )}

      {!!chosen && (
        <Card>
          <H2>Nap</H2>
          {daysWithSlots.size === 0 ? (
            <Muted>Ennél a szakembernél a következő két hétben nincs szabad időpont.</Muted>
          ) : (
            <View style={st.optionRow}>
              {[...daysWithSlots.keys()].sort().map((d) => (
                <Pressable
                  key={d}
                  accessibilityRole="button"
                  accessibilityState={{ selected: day === d }}
                  onPress={() => {
                    setDay(d)
                    setStart(null)
                  }}
                  style={[st.day, day === d && st.optionOn]}
                >
                  <Text style={[st.dayWeekday, day === d && st.optionTextOn]}>
                    {new Date(`${d}T12:00:00Z`).toLocaleDateString('hu-HU', { weekday: 'short' })}
                  </Text>
                  <Text style={[st.dayNumber, day === d && st.optionTextOn]}>
                    {Number(d.slice(8, 10))}
                  </Text>
                  <Text style={[st.dayMonth, day === d && st.optionTextOn]}>
                    {new Date(`${d}T12:00:00Z`).toLocaleDateString('hu-HU', { month: 'short' })}
                  </Text>
                </Pressable>
              ))}
            </View>
          )}
        </Card>
      )}

      {!!day && (
        <Card>
          <H2>Időpont</H2>
          <View style={st.optionRow}>
            {daySlots.map((slot) => (
              <Pressable
                key={slot.start}
                accessibilityRole="button"
                accessibilityLabel={`${formatTime(slot.start)} időpont`}
                accessibilityState={{ selected: start === slot.start }}
                onPress={() => setStart(slot.start)}
                style={[st.slot, start === slot.start && st.optionOn]}
              >
                <Text style={[st.optionText, start === slot.start && st.optionTextOn]}>
                  {formatTime(slot.start)}
                </Text>
              </Pressable>
            ))}
          </View>
        </Card>
      )}

      {!!start && !user && (
        <Card>
          <H2>Adataid</H2>
          <Muted>A visszaigazolást és a belépő linket erre a címre küldjük.</Muted>
          <View style={{ marginTop: spacing.md }}>
            <Field
              label="Vezetéknév"
              value={form.lastName}
              onChangeText={(v) => setForm((f) => ({ ...f, lastName: v }))}
              autoComplete="family-name"
            />
            <Field
              label="Keresztnév"
              value={form.firstName}
              onChangeText={(v) => setForm((f) => ({ ...f, firstName: v }))}
              autoComplete="given-name"
            />
            <Field
              label="E-mail"
              value={form.email}
              onChangeText={(v) => setForm((f) => ({ ...f, email: v }))}
              keyboardType="email-address"
              autoCapitalize="none"
              autoComplete="email"
            />
            <Field
              label="Telefonszám"
              value={form.phone}
              onChangeText={(v) => setForm((f) => ({ ...f, phone: v }))}
              keyboardType="phone-pad"
              autoComplete="tel"
            />
          </View>
        </Card>
      )}

      {!!start && (
        <Card>
          <H2>Fizetési mód</H2>
          {SETTLEMENTS.map((s) => (
            <Pressable
              key={s.value}
              accessibilityRole="radio"
              accessibilityState={{ selected: settlement === s.value }}
              onPress={() => setSettlement(s.value)}
              style={[st.radio, settlement === s.value && st.radioOn]}
            >
              <Text style={st.radioLabel}>{s.label}</Text>
              <Muted>{s.hint}</Muted>
            </Pressable>
          ))}
        </Card>
      )}

      {!!start && (
        <Card>
          <H2>Összegzés</H2>
          <Row label="Kezelés" value={svc.title} />
          <Row label="Szakember" value={chosen?.practitionerName ?? '—'} />
          <Row label="Időpont" value={formatDateTime(start)} />
          <Row label="Időtartam" value={`${svc.time} perc`} />
          <Row
            label="Áfa"
            value={svc.vatRate ? 'bruttó, 27% áfa' : 'áfamentes'}
          />
          <Row label="Fizetendő" value={formatFt(svc.price)} />

          {!!error && (
            <View style={{ marginTop: spacing.md }}>
              <Text style={st.error}>{error}</Text>
            </View>
          )}

          <View style={{ marginTop: spacing.lg }}>
            <Button
              label="Foglalás megerősítése"
              onPress={() => void submit()}
              loading={submitting}
              disabled={!settlement || (!user && !form.email)}
            />
          </View>
        </Card>
      )}
    </ScrollView>
  )
}

const st = StyleSheet.create({
  page: { padding: spacing.md, paddingBottom: spacing.xl },
  optionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.sm },
  option: {
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 12,
    paddingHorizontal: spacing.md,
    minHeight: 48,
    justifyContent: 'center',
  },
  optionOn: { backgroundColor: colors.ink, borderColor: colors.ink },
  optionText: { color: colors.text, fontSize: 15 },
  optionTextOn: { color: colors.onInk, fontWeight: '600' },

  day: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    minWidth: 64,
  },
  dayWeekday: { fontSize: 11, color: colors.textMuted, textTransform: 'uppercase' },
  dayNumber: { fontSize: 20, fontWeight: '700', color: colors.text },
  dayMonth: { fontSize: 11, color: colors.textMuted },

  slot: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 12,
    paddingHorizontal: spacing.md,
    minWidth: 78,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },

  radio: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    marginTop: spacing.sm,
  },
  radioOn: { borderColor: colors.ink, backgroundColor: colors.tint },
  radioLabel: { fontSize: 16, fontWeight: '600', color: colors.text, marginBottom: 2 },

  error: { color: colors.danger, fontSize: 15, lineHeight: 21 },
})

// app/pages/foglalas/[slug].vue
<script setup lang="ts">
/**
 * Foglalási folyamat.
 *
 * Háromlépéses: időpont -> adatok -> megerősítés. Az idősávokat a
 * /api/availability adja (a tesztelt motorból), a foglalást a
 * /api/appointments/hold hozza létre tranzakciós zárolással.
 *
 * A kliens SOHA nem dönt arról, hogy egy idősáv szabad-e: csak azt kínálja fel,
 * amit a szerver visszaadott, és a szerver a létrehozáskor újra ellenőrzi.
 */
const route = useRoute()
const slug = computed(() => String(route.params.slug))

const { data: svcData, error: svcError } = await useFetch<{
  product: {
    id: number
    slug: string
    title: string
    desc: string
    type: string | null
    price: number
    time: number
    vatRate: number
  }
}>(() => `/api/products?slug=${slug.value}`)

const service = computed(() => svcData.value?.product)

// --- állapot ---------------------------------------------------------------
const step = ref<1 | 2 | 3>(1)
const practitionerId = ref<number | null>(null)
const dayOffset = ref<number | null>(null)
const chosenStart = ref<string | null>(null)
const settlement = ref<'ONLINE_CARD' | 'PASS' | 'ON_SITE' | null>(null)
const terms = ref(false)
const submitting = ref(false)
const errorMsg = ref('')
const result = ref<{
  publicRef: string
  startsAt: string
  settlement: string
  needsPayment: boolean
} | null>(null)

const form = reactive({ lastName: '', firstName: '', email: '', phone: '', note: '' })

const { user } = useUserSession()

// --- naptár ----------------------------------------------------------------
const DAYS = ['Vas', 'Hét', 'Ke', 'Sze', 'Csü', 'Pén', 'Szo']
const MONTHS = ['jan', 'feb', 'márc', 'ápr', 'máj', 'jún', 'júl', 'aug', 'szep', 'okt', 'nov', 'dec']
const HORIZON = 21

const dayList = computed(() =>
  Array.from({ length: HORIZON }, (_, i) => {
    const d = new Date()
    d.setHours(0, 0, 0, 0)
    d.setDate(d.getDate() + i)
    return { offset: i, date: d, dow: DAYS[d.getDay()], num: d.getDate(), mon: MONTHS[d.getMonth()] }
  }),
)

const range = computed(() => {
  const from = new Date()
  from.setHours(0, 0, 0, 0)
  const to = new Date(from)
  to.setDate(to.getDate() + HORIZON)
  return { from: from.toISOString(), to: to.toISOString() }
})

interface Slot { start: string; end: string; roomId: number | null }
interface Avail {
  holdMinutes: number
  priceGross: number
  practitioners: { practitionerId: number; practitionerName: string; slots: Slot[] }[]
  reason?: string
}

// Egyetlen lekérés: korábban tévedésből két külön useFetch hívta ugyanezt az
// endpointot, ami dupla kérést és két, egymástól független állapotot adott.
const {
  data: avail,
  status: availStatus,
  refresh: refreshAvail,
} = await useFetch<Avail>('/api/availability', {
  key: 'availability',
  query: computed(() => ({
    serviceId: service.value?.id,
    from: range.value.from,
    to: range.value.to,
  })),
  // A kezelés id-je kell hozzá, ezért csak akkor indul, ha az már megvan
  immediate: Boolean(service.value),
  watch: [service],
})

const practitioners = computed(() => avail.value?.practitioners ?? [])

/** Egy szakember adott napi, még szabad idősávjai. */
function slotsFor(pid: number, offset: number): Slot[] {
  const p = practitioners.value.find((x) => x.practitionerId === pid)
  if (!p) return []
  const d = dayList.value.find((x) => x.offset === offset)!.date
  const next = new Date(d)
  next.setDate(next.getDate() + 1)
  return p.slots.filter((s) => {
    const t = new Date(s.start).getTime()
    return t >= d.getTime() && t < next.getTime()
  })
}

const hasAnySlot = (offset: number) =>
  practitionerId.value ? slotsFor(practitionerId.value, offset).length > 0 : false

const daySlots = computed(() =>
  practitionerId.value !== null && dayOffset.value !== null
    ? slotsFor(practitionerId.value, dayOffset.value)
    : [],
)

const hhmm = (iso: string) =>
  new Intl.DateTimeFormat('hu-HU', {
    hour: '2-digit', minute: '2-digit', hourCycle: 'h23', timeZone: 'Europe/Budapest',
  }).format(new Date(iso))

const longDate = (iso: string) =>
  new Intl.DateTimeFormat('hu-HU', {
    year: 'numeric', month: 'long', day: 'numeric', weekday: 'long', timeZone: 'Europe/Budapest',
  }).format(new Date(iso))

const Ft = (n: number) => new Intl.NumberFormat('hu-HU').format(n) + ' Ft'

// --- lépésváltás -----------------------------------------------------------
function pickPractitioner(id: number) {
  practitionerId.value = id
  dayOffset.value = null
  chosenStart.value = null
}
function pickDay(o: number) {
  dayOffset.value = o
  chosenStart.value = null
}

function toStep2() {
  if (!chosenStart.value) return
  errorMsg.value = ''
  step.value = 2
}

function toStep3() {
  errorMsg.value = ''
  if (!form.lastName || !form.firstName || !form.email || !form.phone) {
    errorMsg.value = 'A név, e-mail és telefonszám megadása kötelező.'
    return
  }
  step.value = 3
}

async function submit() {
  if (!settlement.value || !terms.value || !service.value || !chosenStart.value) return
  submitting.value = true
  errorMsg.value = ''
  try {
    result.value = await $fetch('/api/appointments/hold', {
      method: 'POST',
      body: {
        serviceId: service.value.id,
        practitionerId: practitionerId.value,
        startsAt: chosenStart.value,
        settlement: settlement.value,
        note: form.note || undefined,
        customer: user.value
          ? undefined
          : {
              lastName: form.lastName,
              firstName: form.firstName,
              email: form.email,
              phone: form.phone,
            },
      },
    })
  } catch (e: unknown) {
    const err = e as { data?: { statusMessage?: string }; statusMessage?: string }
    errorMsg.value =
      err.data?.statusMessage ?? err.statusMessage ?? 'A foglalás nem sikerült. Kérlek próbáld újra.'
    // Ha az idősáv közben elkelt, újratöltjük a naptárat, hogy ne kínáljuk fel újra.
    await refreshAvail()
    chosenStart.value = null
    step.value = 1
  } finally {
    submitting.value = false
  }
}

const chosenPractitioner = computed(
  () => practitioners.value.find((p) => p.practitionerId === practitionerId.value)?.practitionerName ?? '—',
)

useSeoMeta({
  title: () => (service.value ? `${service.value.title} – időpontfoglalás | V40 Vital` : 'Időpontfoglalás | V40 Vital'),
  robots: 'noindex',
})
</script>

<template>
  <Header />

  <div class="relative w-full pb-10 pt-12 lg:pt-16 lg:pb-14 lg:px-[100px] bg-[#E5F7F9]">
    <div class="w-full max-w-[1440px] mx-auto flex flex-col items-center p-4 lg:px-0">
      <h1 class="text-[32px] lg:text-[56px] dm-sans font-bold mb-3 text-center text-[#171008]">
        Időpontfoglalás
      </h1>
      <p class="dm-sans text-[#171008] text-[18px] text-center lg:max-w-[540px]">
        {{ service?.title ?? 'Kezelés' }}
      </p>
    </div>
  </div>

  <div class="w-full bg-[#F4F4F0] py-10 lg:py-14 lg:px-[100px]">
    <div class="w-full max-w-[1440px] mx-auto p-4 lg:px-0">
      <div v-if="svcError" class="bg-white rounded-lg p-8 text-center">
        <p class="dm-sans text-[18px]">Ez a kezelés nem elérhető.</p>
        <NuxtLink to="/kezelesek" class="inline-block mt-4 bg-[#153131] text-[#F4F4F0] rounded-lg px-8 py-4 font-medium">
          Vissza a kezelésekhez
        </NuxtLink>
      </div>

      <!-- ---------------- visszaigazolás ---------------- -->
      <div v-else-if="result" class="bg-white rounded-lg p-6 lg:p-10 max-w-[640px] mx-auto">
        <h2 class="dm-sans font-bold text-[26px] mb-2">
          {{ result.needsPayment ? 'Az időpontot fenntartottuk' : 'Foglalás megerősítve' }}
        </h2>
        <p class="dm-sans text-[#00000080] mb-6">
          {{ result.needsPayment
            ? 'A fizetés befejezéséig tartjuk az idősávot.'
            : 'Visszaigazolást küldtünk e-mailben.' }}
        </p>

        <div class="flex justify-between py-2 border-b border-dashed border-[#0000001A] text-[15px]">
          <span>Azonosító</span><b class="font-mono">{{ result.publicRef }}</b>
        </div>
        <div class="flex justify-between py-2 border-b border-dashed border-[#0000001A] text-[15px]">
          <span>Kezelés</span><b>{{ service?.title }}</b>
        </div>
        <div class="flex justify-between py-2 border-b border-dashed border-[#0000001A] text-[15px]">
          <span>Szakember</span><b>{{ chosenPractitioner }}</b>
        </div>
        <div class="flex justify-between py-2 border-b border-dashed border-[#0000001A] text-[15px]">
          <span>Időpont</span><b>{{ longDate(result.startsAt) }}, {{ hhmm(result.startsAt) }}</b>
        </div>
        <div class="flex justify-between py-2 text-[15px]">
          <span>Fizetés</span>
          <b>{{ result.settlement === 'PASS' ? 'bérletből levonva'
            : result.settlement === 'ON_SITE' ? 'helyszínen' : 'bankkártya' }}</b>
        </div>

        <div v-if="result.needsPayment" class="mt-6 bg-[#FDF3EA] text-[#A6541B] rounded-lg p-4 text-[14px]">
          A bankkártyás fizetés még nem elérhető ezen a rendszeren. Az időpontot
          fenntartottuk, kollégánk felveszi veled a kapcsolatot.
        </div>

        <div class="mt-7 flex flex-wrap gap-3">
          <NuxtLink to="/fiok" class="bg-[#153131] text-[#F4F4F0] rounded-lg px-8 py-4 font-medium dm-sans">
            Foglalásaim
          </NuxtLink>
          <NuxtLink to="/kezelesek" class="border-2 border-[#153131] text-[#153131] rounded-lg px-8 py-[14px] font-medium dm-sans">
            További kezelések
          </NuxtLink>
        </div>
      </div>

      <!-- ---------------- folyamat ---------------- -->
      <template v-else>
        <div class="flex flex-wrap gap-2 mb-7">
          <div
            v-for="(t, i) in ['Időpont', 'Adatok', 'Megerősítés']"
            :key="t"
            class="text-[13px] font-semibold rounded-full px-4 py-2 border"
            :class="step === i + 1
              ? 'bg-[#153131] border-[#153131] text-white'
              : step > i + 1
                ? 'bg-[#E5F7F9] border-[#E5F7F9] text-[#153131]'
                : 'bg-white border-[#0000001A] text-[#00000080]'"
          >
            {{ i + 1 }}. {{ t }}
          </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_340px] gap-5 items-start">
          <div class="bg-white rounded-lg p-5 lg:p-8">
            <p v-if="errorMsg" class="mb-5 bg-[#FDF3EA] text-[#A6541B] rounded-lg p-4 text-[14px] font-semibold">
              {{ errorMsg }}
            </p>

            <!-- 1. lépés -->
            <template v-if="step === 1">
              <h3 class="dm-sans font-bold text-[20px] mb-3">Szakember</h3>
              <p v-if="availStatus === 'pending'" class="text-[#00000080]">Szabad időpontok betöltése…</p>
              <p v-else-if="!practitioners.length" class="text-[#00000080]">
                {{ avail?.reason ?? 'Ehhez a kezeléshez jelenleg nincs elérhető szakember.' }}
              </p>
              <div v-else class="flex flex-wrap gap-2">
                <button
                  v-for="p in practitioners"
                  :key="p.practitionerId"
                  class="rounded-full px-4 py-2 text-[14px] border"
                  :class="p.practitionerId === practitionerId
                    ? 'bg-[#153131] border-[#153131] text-white font-semibold'
                    : 'bg-white border-[#0000001A] text-[#00000080]'"
                  @click="pickPractitioner(p.practitionerId)"
                >
                  {{ p.practitionerName }}
                </button>
              </div>

              <template v-if="practitionerId !== null">
                <h3 class="dm-sans font-bold text-[20px] mt-8 mb-3">Nap</h3>
                <div class="flex gap-2 overflow-x-auto pb-2">
                  <button
                    v-for="d in dayList"
                    :key="d.offset"
                    class="shrink-0 w-[74px] rounded-lg border py-2.5 text-center"
                    :class="[
                      d.offset === dayOffset ? 'bg-[#153131] border-[#153131] text-white' : 'bg-white border-[#0000001A]',
                      hasAnySlot(d.offset) ? '' : 'opacity-40 cursor-not-allowed',
                    ]"
                    :disabled="!hasAnySlot(d.offset)"
                    @click="pickDay(d.offset)"
                  >
                    <small class="block text-[11px] uppercase tracking-wide"
                      :class="d.offset === dayOffset ? 'text-white/70' : 'text-[#00000080]'">{{ d.dow }}</small>
                    <b class="dm-sans text-[19px]">{{ d.num }}</b>
                    <span class="block text-[11px]"
                      :class="d.offset === dayOffset ? 'text-white/70' : 'text-[#00000080]'">{{ d.mon }}</span>
                  </button>
                </div>

                <template v-if="dayOffset !== null">
                  <h3 class="dm-sans font-bold text-[20px] mt-6 mb-3">Időpont</h3>
                  <div class="flex flex-wrap gap-2">
                    <button
                      v-for="s in daySlots"
                      :key="s.start"
                      class="rounded-lg border px-4 py-3 min-w-[80px] font-semibold"
                      :class="s.start === chosenStart
                        ? 'bg-[#153131] border-[#153131] text-white'
                        : 'bg-white border-[#0000001A]'"
                      @click="chosenStart = s.start"
                    >
                      {{ hhmm(s.start) }}
                    </button>
                  </div>
                  <p class="text-[#00000080] text-[14px] mt-4">
                    A kezelés {{ service?.time }} perc. A megjelenő időpontok már tartalmazzák
                    az előkészítési időt.
                  </p>
                </template>
              </template>

              <div class="mt-8">
                <button
                  class="bg-[#153131] text-[#F4F4F0] rounded-lg px-8 py-4 font-medium dm-sans disabled:opacity-40"
                  :disabled="!chosenStart"
                  @click="toStep2"
                >
                  Tovább az adatokhoz
                </button>
              </div>
            </template>

            <!-- 2. lépés -->
            <template v-else-if="step === 2">
              <h3 class="dm-sans font-bold text-[20px] mb-4">Adataid</h3>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label class="block text-[13px] font-bold mb-1.5">Vezetéknév *</label>
                  <input v-model="form.lastName" type="text" class="w-full border border-[#0000001A] rounded-lg px-3 py-3" />
                </div>
                <div>
                  <label class="block text-[13px] font-bold mb-1.5">Keresztnév *</label>
                  <input v-model="form.firstName" type="text" class="w-full border border-[#0000001A] rounded-lg px-3 py-3" />
                </div>
              </div>
              <div class="mt-4">
                <label class="block text-[13px] font-bold mb-1.5">E-mail *</label>
                <input v-model="form.email" type="email" class="w-full border border-[#0000001A] rounded-lg px-3 py-3" />
                <p class="text-[12px] text-[#00000080] mt-1.5">
                  Ide küldjük a visszaigazolást és a belépő linket – nem kell jelszót kitalálnod.
                </p>
              </div>
              <div class="mt-4">
                <label class="block text-[13px] font-bold mb-1.5">Telefonszám *</label>
                <input v-model="form.phone" type="tel" class="w-full border border-[#0000001A] rounded-lg px-3 py-3" />
              </div>
              <div class="mt-4">
                <label class="block text-[13px] font-bold mb-1.5">Megjegyzés a rendelőnek</label>
                <textarea v-model="form.note" rows="3" class="w-full border border-[#0000001A] rounded-lg px-3 py-3" />
              </div>

              <div class="mt-6 flex flex-wrap gap-3">
                <button class="bg-[#153131] text-[#F4F4F0] rounded-lg px-8 py-4 font-medium dm-sans" @click="toStep3">
                  Tovább
                </button>
                <button class="text-[#00000080] underline py-4" @click="step = 1">Vissza</button>
              </div>
            </template>

            <!-- 3. lépés -->
            <template v-else>
              <h3 class="dm-sans font-bold text-[20px] mb-4">Fizetési mód</h3>

              <label
                v-for="opt in [
                  { v: 'ON_SITE', t: 'Fizetés a helyszínen', d: 'Készpénz vagy bankkártya a rendelőben. Az időpont azonnal megerősítésre kerül.' },
                  { v: 'PASS', t: 'Bérletből levonás', d: 'Ha van érvényes bérleted erre a kezelésre, a rendszer levon egy alkalmat.' },
                  { v: 'ONLINE_CARD', t: 'Bankkártyás fizetés (hamarosan)', d: 'A kártyás fizetés még nincs élesítve. Az időpontot fenntartjuk, és felkeresünk.' },
                ]"
                :key="opt.v"
                class="flex gap-3 items-start bg-white border-2 rounded-lg p-4 mb-3 cursor-pointer"
                :class="settlement === opt.v ? 'border-[#153131]' : 'border-[#0000001A]'"
              >
                <input v-model="settlement" type="radio" :value="opt.v" class="mt-1 w-[17px] h-[17px] accent-[#153131]" />
                <span>
                  <b class="block text-[15px]">{{ opt.t }}</b>
                  <span class="text-[#00000080] text-[13.5px]">{{ opt.d }}</span>
                </span>
              </label>

              <label class="flex gap-3 items-start my-5 text-[14px] cursor-pointer">
                <input v-model="terms" type="checkbox" class="mt-1 w-[17px] h-[17px] accent-[#153131]" />
                <span>
                  Elfogadom az <NuxtLink to="/aszf" class="underline">ÁSZF</NuxtLink>-et és az
                  <NuxtLink to="/adatvedelmi" class="underline">Adatkezelési tájékoztatót</NuxtLink>.
                </span>
              </label>

              <div class="flex flex-wrap gap-3">
                <button
                  class="bg-[#153131] text-[#F4F4F0] rounded-lg px-8 py-4 font-medium dm-sans disabled:opacity-40"
                  :disabled="!settlement || !terms || submitting"
                  @click="submit"
                >
                  {{ submitting ? 'Foglalás…' : 'Foglalás megerősítése' }}
                </button>
                <button class="text-[#00000080] underline py-4" @click="step = 2">Vissza</button>
              </div>
            </template>
          </div>

          <!-- összegző -->
          <div class="bg-white rounded-lg p-5 lg:sticky lg:top-6">
            <h4 class="dm-sans font-bold text-[16px] mb-4">Összegzés</h4>
            <div class="flex justify-between gap-3 py-2 border-b border-dashed border-[#0000001A] text-[14px]">
              <span>Kezelés</span><b class="text-right">{{ service?.title }}</b>
            </div>
            <div class="flex justify-between gap-3 py-2 border-b border-dashed border-[#0000001A] text-[14px]">
              <span>Szakember</span><b class="text-right">{{ chosenPractitioner }}</b>
            </div>
            <div class="flex justify-between gap-3 py-2 border-b border-dashed border-[#0000001A] text-[14px]">
              <span>Időpont</span>
              <b class="text-right">{{ chosenStart ? `${longDate(chosenStart)}, ${hhmm(chosenStart)}` : '—' }}</b>
            </div>
            <div class="flex justify-between gap-3 py-2 border-b border-dashed border-[#0000001A] text-[14px]">
              <span>Időtartam</span><b>{{ service?.time }} perc</b>
            </div>
            <div class="flex justify-between gap-3 py-2 text-[14px]">
              <span>Áfa</span><b>{{ service?.vatRate ? '27%' : 'áfamentes' }}</b>
            </div>
            <div class="flex justify-between mt-3 pt-3 border-t-2 border-[#171008] dm-sans font-bold text-[19px]">
              <span>Fizetendő</span>
              <span>{{ settlement === 'PASS' ? '1 alkalom' : Ft(service?.price ?? 0) }}</span>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>

  <WFooter />
</template>
